spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${db_password}
    url: jdbc:mysql://localhost:3306/mobilelele?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ${db_username}
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf: # Thymeleaf
      cache: false
      mode: HTML
      encoding: UTF-8
      prefix: file:src/main/resources/templates/
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
  sql:
    init:
      mode: never

  mvc:
    hidden method:
      filter:
        enabled: true
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
#    org.springframework: debug

open.exchange.rates:
  schema: https
  host: openexchangerates.org
  path: /api/latest.json
  app_id: ${APP_ID}
  symbols: EUR,BGN
  enabled: false

mobilele:
  remember.me.key: ${REMEMBER_ME_KEY}

mail:
  mobilele: "mobilele@example.com"
  host: localhost
  port: 1025
  username: ${MAIL_USER}
  password: ${MAIL_PASSWORD}

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

google.recaptcha:
  key: ${RECAPTCHA_SITE_KEY:test}
  secret: ${RECAPTCHA_SITE_SECRET:test}